/*
 * This source file was generated by the Gradle 'init' task
 */
package cookbook;

import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        System.setProperty("awt.useSystemAAFontSettings", "on");
        System.setProperty("swing.aatext", "true");

        SwingUtilities.invokeLater(CookbookGUI::new);
    }
}
