/*
 * This source file was generated by the Gradle 'init' task
 */
package cookbook;

import java.util.Scanner;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(App.getGreeting());
    }
}
